language: python
branches:
  only:
  - master
git:
  depth: 1
install:
- pip install mkdocs
- pip install mkdocs-material
script:
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then mkdocs build --strict; fi;
deploy: 
  skip_cleanup: true
  provider: script
  script: bash travis-ci/deploy-to-gh-pages.sh
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST == "false"
