language: python
branches:
  only:
  - master
git:
  depth: false
install:
- pip install mkdocs
- pip install mkdocs-material
script:
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then mkdocs build --strict; fi;
- openssl aes-256-cbc -K $encrypted_41526d4b983e_key -iv $encrypted_41526d4b983e_iv -in github_deploy_mkdocs_id_ed25519.enc -out ./github_deploy_mkdocs_id_ed25519 -d
- chmod 600 github_deploy_mkdocs_id_ed25519
- eval `ssh-agent -s`
- ssh-add github_deploy_mkdocs_id_ed25519
- git config user.name "Travis CI"
- git config user.email "agarthetiger@users.noreply.github.com"
- git --version
- git remote show origin
- git remote set-branches --add origin gh-pages
- git fetch origin
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "Publishing to GitHub Pages site on gh-pages branch."; mkdocs gh-deploy; fi;