language: python
branches:
  only:
  - master
git:
  depth: 1
install:
- pip install -r requirements.txt
script:
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then mkdocs build --strict; fi;
deploy: 
  skip_cleanup: true
  provider: script
  script: bash travis-ci/deploy-to-gh-pages.sh
  on:
    branch: master
