site_name: Software Engineering Notes
site_url: https://agarthetiger.github.io/mkdocs/

repo_name: 'agarthetiger/mkdocs'
repo_url: 'https://github.com/agarthetiger/mkdocs'

edit_uri: 'blob/master/docs/'

theme: 
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  
extra:
  social:
    - type: github-alt
      link: https://github.com/agarthetiger
    - type: linkedin
      link: https://uk.linkedin.com/in/buildthethingright
